export default <AppItem[]>[
  {
    homepage: 'https://www.figma.com/',
    repository: 'https://github.com/figma',
    icon: 'figma.png',
    keywords: ['figma'],
    name: 'Figma',
  },
  {
    homepage: 'https://mastergo.com/',
    repository: 'https://github.com/mastergo-design',
    icon: 'mastergo.png',
    keywords: ['mastergo'],
    name: 'MasterGo',
  },
  {
    homepage: 'https://js.design/',
    repository: 'https://github.com/jsdesigndev',
    icon: 'jishidesign.png',
    keywords: ['jishidesign', '即时设计'],
    name: '即时设计',
  },
  {
    homepage: 'https://modao.cc/',
    icon: 'modao.png',
    keywords: ['modao'],
    name: '墨刀',
    lessRadius: true,
  },
  {
    homepage: 'https://www.processon.com/',
    icon: 'processon.png',
    keywords: ['processon'],
    name: 'ProcessOn',
  },
  {
    homepage: 'https://www.zcool.com.cn/',
    icon: 'zcool.png',
    keywords: ['zcool', '站酷'],
    name: '站酷',
  },
  {
    homepage: 'https://huaban.com/',
    icon: 'huaban.png',
    keywords: ['huaban', '花瓣'],
    name: '花瓣',
  },
  {
    homepage: 'https://dribbble.com/',
    repository: 'https://github.com/dribbble',
    icon: 'dribbble.png',
    keywords: ['dribbble'],
    name: 'Dribbble',
  },
  {
    homepage: 'https://www.pinterest.com/',
    repository: 'https://github.com/pinterest',
    icon: 'pinterest.png',
    keywords: ['pinterest'],
    name: 'Pinterest',
  },
  {
    homepage: 'https://www.behance.net/',
    repository: 'https://github.com/behance',
    icon: 'behance.png',
    keywords: ['behance'],
    name: 'Behance',
  },
  {
    homepage: 'https://craftwork.design/',
    icon: 'craftwork.png',
    keywords: ['craftwork'],
    name: 'Craftwork',
    darkInvert: true,
  },
  {
    homepage: 'https://mobbin.com/',
    repository: 'https://github.com/mobbin',
    icon: 'mobbin.png',
    keywords: ['mobbin'],
    name: 'Mobbin',
    darkInvert: true,
  },
  {
    homepage: 'https://discover.gumroad.com/',
    repository: 'https://github.com/gumroad',
    icon: 'gumroad.png',
    keywords: ['gumroad'],
    name: 'Gumroad',
  },
  {
    homepage: 'https://www.ui8.net/',
    icon: 'ui8.png',
    keywords: ['ui8'],
    name: 'UI8',
  },
  {
    homepage: 'https://layers.to/',
    icon: 'layers.png',
    keywords: ['layers'],
    name: 'Layers',
    darkInvert: true,
  },];