export default <AppItem[]>[
  {
    homepage: 'https://pinia.vuejs.org/',
    repository: 'https://github.com/posva/pinia',
    icon: 'pinia.png',
    keywords: ['pinia'],
    name: 'Pinia',
  },
  {
    homepage: [
      { href: 'https://www.redux.org.cn/', title: '中文网' },
      { href: 'https://redux.js.org/', title: '官网' },
    ],
    repository: 'https://github.com/reduxjs/redux',
    icon: 'redux.png',
    keywords: ['redux'],
    name: 'Redux',
  },
  {
    homepage: 'https://reacttraining.com/react-router/',
    repository: 'https://github.com/ReactTraining/react-router',
    icon: 'react-router.png',
    keywords: ['reactrouter'],
    name: 'ReactRouter',
  },
  {
    homepage: 'https://graphql.org/',
    repository: 'https://github.com/graphql/graphiql',
    icon: 'graphql.png',
    keywords: ['graphql'],
    name: 'GraphQL',
  },
  {
    homepage: 'https://www.apollographql.com/',
    repository: 'https://github.com/apollographql',
    icon: 'apollographql.png',
    keywords: ['apollographql'],
    name: 'Apollo',
  },
  {
    homepage: 'https://lerna.js.org/',
    repository: 'https://github.com/lerna/lerna',
    icon: 'lerna.png',
    keywords: ['lerna'],
    name: 'Lerna',
    darkInvert: true,
  },
  {
    homepage: 'https://pre-commit.com/',
    repository: 'https://github.com/pre-commit/pre-commit',
    icon: 'pre-commit.png',
    keywords: ['pre-commit'],
    name: 'PreCommit',
  },
  {
    homepage: [
      { href: 'https://www.lodashjs.com/', title: '中文网' },
      { href: 'https://lodash.com/', title: '英文官网' },
    ],
    repository: 'https://github.com/lodash/lodash/',
    icon: 'lodash.png',
    keywords: ['lodash'],
    name: 'Lodash',
  },
  {
    homepage: 'https://vueuse.org/',
    repository: 'https://github.com/vueuse/vueuse',
    icon: 'vueuse.png',
    keywords: ['vueuse'],
    name: 'VueUse',
  },
  {
    homepage: 'https://ahooks.js.org/',
    repository: 'https://github.com/alibaba/hooks',
    icon: 'ahooks.png',
    keywords: ['ahooks', 'react'],
    name: 'Ahooks',
  },
  {
    homepage: 'https://dojotoolkit.org/',
    repository: 'https://github.com/dojo/dojo',
    icon: 'dojo.png',
    keywords: ['dojo'],
    name: 'Dojo',
  },
  {
    homepage: 'https://immutable-js.github.io/immutable-js/',
    repository: 'https://github.com/immutable-js/immutable-js',
    icon: 'immutable.png',
    keywords: ['immutable'],
    name: 'Immutable',
  },
  {
    homepage: 'https://jquery.com/',
    repository: 'https://github.com/jquery/jquery',
    icon: 'jquery.png',
    keywords: ['jquery'],
    name: 'jQuery',
  },
  {
    homepage: 'https://zeptojs.com/',
    repository: 'https://github.com/madrobby/zepto/',
    icon: 'zepto.png',
    keywords: ['zepto'],
    name: 'Zepto',
  },
  {
    homepage: 'https://axios-http.com/',
    repository: 'https://github.com/axios/axios',
    icon: 'axios.png',
    keywords: ['axios'],
    name: 'Axios',
    darkInvert: true,
  },
  {
    homepage: 'http://mockjs.com/',
    repository: 'https://github.com/nuysoft/Mock',
    icon: 'mockjs.png',
    keywords: ['mockjs'],
    name: 'MockJS',
  },
  {
    homepage: 'https://fakerjs.dev/',
    repository: 'https://github.com/faker-js/faker',
    icon: 'faker.png',
    keywords: ['faker'],
    name: 'faker',
  },
  {
    homepage: 'https://momentjs.com/',
    repository: 'https://github.com/moment/moment',
    icon: 'moment.png',
    keywords: ['moment'],
    name: 'Moment',
  },
  {
    homepage: 'https://day.js.org/',
    repository: 'https://github.com/iamkun/dayjs',
    icon: 'dayjs.png',
    keywords: ['dayjs'],
    name: 'DayJS',
  },
  {
    homepage: 'https://date-fns.org/',
    repository: 'https://github.com/date-fns/date-fns',
    icon: 'date-fns.png',
    keywords: ['date-fns'],
    name: 'DateFNS',
  },
  {
    homepage: 'https://mochajs.org/',
    repository: 'https://github.com/mochajs/mocha',
    icon: 'mocha.png',
    keywords: ['mocha'],
    name: 'Mocha',
  },
  {
    homepage: 'https://testing-library.com/',
    repository: 'https://github.com/testing-library',
    icon: 'testing-library.png',
    keywords: ['testing-library'],
    name: 'TestingLibrary',
  },
  {
    homepage: 'https://www.cypress.io/',
    repository: 'https://github.com/cypress-io/cypress',
    icon: 'cypress.png',
    keywords: ['cypress'],
    name: 'Cypress',
  },
  {
    homepage: 'https://ava.li/',
    repository: 'https://github.com/avajs/ava',
    icon: 'ava.png',
    keywords: ['ava'],
    name: 'AVA',
  },
  {
    homepage: 'https://miragejs.com/',
    repository: 'https://github.com/miragejs',
    icon: 'mirage.png',
    keywords: ['mirage'],
    name: 'Mirage',
  },
  {
    homepage: [
      {
        href: 'https://highlightjs.org/',
        title: '官网',
      },
      {
        href: 'https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md',
        title: '支持语言列表',
      },
    ],
    repository: 'https://github.com/highlightjs/highlight.js',
    icon: 'hljs.png',
    keywords: [
      'highlightjs',
      'highlight.js',
      'hljs',
      '代码',
      '高亮',
      'highlight',
    ],
    name: 'HighlightJS',
  },
  {
    homepage: 'http://logic-flow.org/',
    repository: 'https://github.com/didi/LogicFlow',
    icon: 'logic-flow.png',
    keywords: ['logic-flow'],
    name: 'LogicFlow',
  },
  {
    homepage: 'https://threejs.org/',
    repository: 'https://github.com/mrdoob/three.js/',
    icon: 'three.js.png',
    keywords: ['threejs', 'three.js'],
    name: 'ThreeJS',
    darkInvert: true,
  },
  {
    homepage: 'https://pptr.dev/',
    repository: 'https://github.com/GoogleChrome/puppeteer',
    icon: 'puppeteer.png',
    keywords: ['pptr', 'puppeteer'],
    name: 'Puppeteer',
  },
  {
    homepage: 'https://yeoman.io/',
    repository: 'https://github.com/yeoman/yo',
    icon: 'yeoman.png',
    keywords: ['yo', 'yeoman'],
    name: 'Yeoman',
  },
  {
    homepage: 'https://socket.io/',
    repository: 'https://github.com/socketio/socket.io',
    icon: 'socket-io.png',
    keywords: ['socketio'],
    name: 'SocketIO',
  },
  {
    homepage: 'http://docs.sequelizejs.com/',
    repository: 'https://github.com/sequelize/sequelize',
    icon: 'sequelize.png',
    keywords: ['sequelize'],
    name: 'Sequelize',
  },
  {
    homepage: 'https://webassembly.org/',
    repository: 'https://github.com/WebAssembly',
    icon: 'webassembly.png',
    keywords: ['WebAssembly'],
    name: 'WebAssembly',
  },
  {
    homepage: 'https://requirejs.org/',
    repository: 'https://github.com/requirejs/requirejs',
    icon: 'requirejs.png',
    keywords: ['requirejs'],
    name: 'requirejs',
  },
  {
    homepage: 'https://d3js.org/',
    repository: 'https://github.com/d3/d3',
    icon: 'd3js.svg',
    keywords: ['d3js'],
    name: 'd3js',
  },
  {
    homepage: 'https://router.vuejs.org/',
    repository: 'https://github.com/vuejs/router',
    icon: 'vue.png',
    keywords: ['vuerouter'],
    name: 'Vue Router',
    lessRadius: true,
  },
  {
    homepage: 'https://react-redux.js.org/',
    repository: 'https://github.com/reduxjs/react-redux',
    icon: 'redux.png',
    keywords: ['redux'],
    name: 'React Redux',
  },
  {
    homepage: 'https://zustand-demo.pmnd.rs/',
    repository: 'https://github.com/pmndrs/zustand',
    icon: 'zustand.png',
    keywords: ['zustand'],
    name: 'Zustand',
  },
  {
    homepage: 'https://mobx.js.org/',
    repository: 'https://github.com/mobxjs/mobx',
    icon: 'mobx.png',
    keywords: ['mobx'],
    name: 'MobX',
  },
  {
    homepage: 'https://inhiblabcore.github.io/vue-hooks-plus/',
    repository: 'https://github.com/InhiblabCore/vue-hooks-plus',
    icon: 'vue-hooks-plus.png',
    keywords: ['vuehooksplus'],
    name: 'VueHooks Plus',
    lessRadius: true,
  },
  {
    homepage: 'https://vue-vine.dev/',
    repository: 'https://github.com/vue-vine/vue-vine',
    icon: 'vue-vine.png',
    keywords: ['vue-vine'],
    name: 'Vue Vine',
  },
  {
    homepage: 'https://playwright.dev/',
    repository: 'https://github.com/microsoft/playwright',
    icon: 'playwright.png',
    keywords: ['playwright'],
    name: 'playwright',
  },
  {
    homepage: 'https://vitest.dev/',
    repository: 'https://github.com/vitest-dev/vitest',
    icon: 'vitest.png',
    keywords: ['vitest'],
    name: 'Vitest',
  },
  {
    homepage: 'https://rstest.rs/',
    repository: 'https://github.com/web-infra-dev/rstest',
    icon: 'rstest.png',
    keywords: ['rstest'],
    name: 'Rstest',
  },
  {
    homepage: 'https://react-hook-form.com/',
    repository: 'https://github.com/react-hook-form/react-hook-form',
    icon: 'react-hook-form.png',
    keywords: ['react-hook-form'],
    name: 'ReactHookForm',
  },
  {
    homepage: 'https://zod.dev/',
    repository: 'https://github.com/colinhacks/zod',
    icon: 'zod.png',
    keywords: ['zod'],
    name: 'Zod',
  },
  {
    homepage: 'https://joi.dev/',
    repository: 'https://github.com/hapijs/joi',
    icon: 'joi.png',
    keywords: ['joi'],
    name: 'Joi',
  },
  {
    homepage: 'https://underscorejs.org/',
    repository: 'https://github.com/jashkenas/underscore',
    icon: 'underscore.png',
    keywords: ['underscore'],
    name: 'Underscore',
    lessRadius: true,
  },
  {
    homepage: 'https://radash-docs.vercel.app/',
    repository: 'https://github.com/sodiray/radash',
    icon: 'radash.png',
    keywords: ['radash'],
    name: 'Radash',
    lessRadius: true,
  },
  {
    homepage: 'https://github.com/sindresorhus/ky',
    repository: 'https://github.com/sindresorhus/ky',
    icon: 'ky.png',
    keywords: ['ky'],
    name: 'Ky',
  },
  {
    homepage: 'https://swr.vercel.app/',
    repository: 'https://github.com/vercel/swr',
    icon: 'swr.png',
    keywords: ['swr'],
    name: 'SWR',
    darkInvert: true,
  },
  {
    homepage: 'https://marked.js.org/',
    repository: 'https://github.com/markedjs/marked',
    icon: 'marked.png',
    keywords: ['marked'],
    name: 'marked',
    darkInvert: true,
    lessRadius: true,
  },
  {
    homepage: 'https://shiki.style/',
    repository: 'https://github.com/shikijs/shiki',
    icon: 'shiki.png',
    keywords: ['shiki', 'highlight'],
    name: 'Shiki',
  },
  {
    homepage: 'https://diffs.com/',
    repository: 'https://github.com/pierrecomputer/pierre',
    icon: 'diffs.png',
    keywords: ['diffs'],
    name: 'Diffs',
  },
  {
    homepage: 'https://gsap.com/',
    repository: 'https://github.com/greensock/GSAP',
    icon: 'greensock.png',
    keywords: ['greensock', 'gsap'],
    name: 'GreenSock',
  },
  {
    homepage: 'https://tresjs.org/',
    repository: 'https://github.com/Tresjs/tres',
    icon: 'tresjs.png',
    keywords: ['tresjs'],
    name: 'TresJS',
  },
  {
    homepage: 'https://www.remotion.dev/',
    repository: 'https://github.com/remotion-dev/remotion',
    icon: 'remotion.png',
    keywords: ['remotion'],
    name: 'Remotion',
  },
  {
    homepage: 'https://www.prisma.io/',
    repository: 'https://github.com/prisma/prisma',
    icon: 'prisma.png',
    keywords: ['prisma', 'orm'],
    name: 'Prisma',
    darkInvert: true,
  },
  {
    homepage: 'https://typeorm.io/',
    repository: 'https://github.com/typeorm/typeorm',
    icon: 'typeorm.png',
    keywords: ['typeorm', 'orm'],
    name: 'TypeORM',
  },
  {
    homepage: 'https://orm.drizzle.team/',
    repository: 'https://github.com/drizzle-team/drizzle-orm',
    icon: 'drizzle.png',
    keywords: ['drizzle', 'orm'],
    name: 'Drizzle',
    darkInvert: true,
  },
  {
    homepage: 'https://knexjs.org/',
    repository: 'https://github.com/knex/knex',
    icon: 'knex.png',
    keywords: ['knex', 'orm'],
    name: 'Knex.js',
  },
  {
    homepage: 'https://vincit.github.io/objection.js/',
    repository: 'https://github.com/vincit/objection.js',
    icon: 'objection.png',
    keywords: ['objection', 'orm'],
    name: 'Objection.js',
  },
];
