export default <AppItem[]>[
  {
    homepage: 'https://www.imgcook.com/',
    icon: 'imgcook.png',
    keywords: ['imgCook'],
    name: 'imgCook',
  },
  {
    homepage:
      'https://auth.huaweicloud.com/authui/login.html?service=https%3A%2F%2Fconsole.huaweicloud.com%2Fwebmobile%2F%3Fregion%3Dcn-north-4%26cloud_route_state%3D%2Fcloudsite%2FfittingRoom#/login',
    repository: '',
    icon: '',
    keywords: [],
    name: '华为云建站',
  },
  {
    homepage: 'https://lanhuapp.com/',
    repository: '',
    icon: '',
    keywords: [],
    name: '蓝狐',
  },
  {
    homepage: 'https://code.fun',
    repository: '',
    icon: '',
    keywords: [],
    name: 'codeFun',
  },
  {
    homepage: 'https://lab.lowcode-engine.cn/#/',
    repository: '',
    icon: '',
    keywords: [],
    name: 'lab-lowcode',
  },
  {
    homepage: 'https://opentiny.design/tiny-engine#/tiny-engine-editor',
    repository: '',
    icon: '',
    keywords: [],
    name: 'opentiny',
  },
  {
    homepage: 'https://cloud.tencent.com/product/weda',
    repository: '',
    icon: '',
    keywords: [],
    name: 'weda',
  },
  {
    homepage: 'https://www.functorz.com/',
    repository: '',
    icon: '',
    keywords: [],
    name: 'functorz',
  },
  {
    homepage: 'https://mozi-login.alibaba-inc.com/ssoLogin.htm',
    repository: '',
    icon: '',
    keywords: [],
    name: 'mozi',
  },
];
