export default <AppItem[]>[
  {
    homepage: 'https://developers.weixin.qq.com/doc/',
    icon: 'wechatmp.png',
    keywords: [
      '微信小程序',
      '微信开放平台',
      'weixin',
      'wechat',
      'xiaochengxu',
      'miniapp',
      'microapp',
    ],
    name: '微信开放平台',
  },
  {
    homepage: 'https://q.qq.com/',
    icon: 'qqmp.png',
    keywords: ['qq开放平台', 'qq', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: 'QQ开放平台',
  },
  {
    homepage: 'https://open.alipay.com/',
    icon: 'alipaymp.png',
    keywords: [
      '支付宝开放平台',
      '支付宝小程序',
      'zhifubao',
      'alipay',
      'xiaochengxu',
      'miniapp',
      'miniprogram',
      'microapp',
      'mp',
    ],
    name: '支付宝开放平台',
  },
  {
    homepage: 'https://open.dingtalk.com/',
    icon: 'dingtalk.png',
    keywords: ['dingding', 'dingtalk', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '钉钉开放平台',
  },
  {
    homepage: 'https://open.feishu.cn/',
    icon: 'feishu.png',
    keywords: ['feishu', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '飞书开放平台',
  },
  {
    homepage: 'https://open.kuaishou.com/',
    icon: 'kuaishou.png',
    keywords: ['kuaishou', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '快手开放平台',
  },
  {
    homepage: 'https://mp.jd.com/',
    icon: 'jdmp.png',
    keywords: [
      '京东小程序',
      'jingdong',
      'jdmp',
      'xiaochengxu',
      'miniapp',
      'microapp',
    ],
    name: '京东开放平台',
  },
  {
    homepage: 'https://smartprogram.baidu.com/developer/index.html',
    icon: 'bdmp.png',
    keywords: ['百度智能小程序', 'baidu', 'xiaochengxu', 'miniapp', 'microapp'],
    name: '百度开放平台',
  },
  {
    homepage: 'https://developer.open-douyin.com/',
    icon: 'douyin.png',
    keywords: ['抖音开放平台', 'douyin',
      '字节小程序',
      '字节跳动小程序',
      'bytedance', 'xiaochengxu', 'miniapp', 'miniprogram', 'microapp', 'mp'],
    name: '抖音开放平台',
  },
  {
    homepage: 'https://uniapp.dcloud.net.cn/',
    repository: 'https://github.com/dcloudio/uni-app',
    icon: 'uniapp.png',
    keywords: ['app', 'uni', 'uniapp', 'uni-app'],
    name: 'UNI-APP',
  },
  {
    homepage: 'https://mpxjs.cn/',
    repository: 'https://github.com/didi/mpx',
    icon: 'mpx.png',
    keywords: ['mpx'],
    name: 'Mpx',
  },
  {
    homepage: 'https://www.quickapp.cn/quickAppShow',
    icon: 'kyy.png',
    keywords: ['快应用', 'kuaiyingyong'],
    name: '快应用',
  },
]