export default <AppItem[]>[
  {
    homepage: 'https://golang.org/',
    repository: 'https://github.com/golang/go/',
    icon: 'golang.png',
    keywords: ['golang'],
    name: 'Golang',
  },
  {
    homepage: 'https://www.rust-lang.org/',
    repository: 'https://github.com/rust-lang/rust',
    icon: 'rust.png',
    keywords: ['rust'],
    name: 'Rust',
    darkInvert: true,
  },
  {
    homepage: 'https://ziglang.org/',
    repository: 'https://github.com/ziglang/zig',
    icon: 'zig.png',
    keywords: ['zig'],
    name: 'Zig',
  },
  {
    homepage: 'https://www.ruby-lang.org/',
    repository: 'https://github.com/ruby/ruby/',
    icon: 'ruby.png',
    keywords: ['ruby'],
    name: 'Ruby',
  },
  {
    homepage: 'https://www.dartlang.org/',
    repository: 'https://github.com/dart-lang/',
    icon: 'dart.png',
    keywords: ['dart'],
    name: 'Dart',
  },
  {
    homepage: 'https://www.python.org/',
    repository: 'https://github.com/python',
    icon: 'python.png',
    keywords: ['python'],
    name: 'Python',
  },
  {
    homepage: 'https://www.php.net/',
    repository: 'https://github.com/php',
    icon: 'php.png',
    keywords: ['php'],
    name: 'PHP',
  },
  {
    homepage: 'https://www.docker.com/',
    repository: 'https://github.com/docker',
    icon: 'docker.png',
    keywords: ['docker'],
    name: 'Docker',
  },
  {
    homepage: 'http://nginx.org/',
    repository: 'https://github.com/nginx',
    icon: 'nginx.png',
    keywords: ['nginx'],
    name: 'Nginx',
  },
  {
    homepage: [
      { href: 'https://redis.io/', title: '官网' },
      {
        href: 'https://github.com/microsoftarchive/redis/releases',
        title: 'Windows本地下载',
      },
    ],
    repository: 'https://github.com/redis',
    icon: 'redis.png',
    keywords: ['redis'],
    name: 'Redis',
  },
  {
    homepage: 'https://spring.io/',
    repository: 'https://github.com/spring-projects',
    icon: 'spring.png',
    keywords: ['spring'],
    name: 'Spring',
  },
  {
    homepage: 'https://hadoop.apache.org/',
    repository: 'https://github.com/apache/hadoop',
    icon: 'hadoop.png',
    keywords: ['hadoop'],
    name: 'Hadoop',
  },
  {
    homepage: 'https://www.mysql.com/',
    repository: 'https://github.com/mysql',
    icon: 'mysql.png',
    keywords: ['mysql'],
    name: 'MySQL',
  },
  {
    homepage: 'https://www.mongodb.com/',
    repository: 'https://github.com/mongodb',
    icon: 'mongodb.png',
    keywords: ['mongodb'],
    name: 'MongoDB',
  },
  {
    homepage: 'http://www.mongoosejs.net/',
    repository: 'https://github.com/Automattic/mongoose',
    icon: 'mongoose.png',
    keywords: ['mongodb', 'mongoose', 'mongoosejs'],
    name: 'Mongoose',
  },
  {
    homepage: 'https://v8.dev/',
    repository: 'https://github.com/v8/v8',
    icon: 'v8.png',
    keywords: ['v8'],
    name: 'V8',
  },
  {
    homepage: 'https://cn.serverless.com/',
    icon: 'https://uploads-ssl.webflow.com/612dc053b05ed1788ee00cd8/620d418923218e552502b236_6182addc1ae46f185d517c7f_console-icon-outline.svg',
    keywords: ['serverless'],
    name: 'serverless',
  },
  {
    homepage: 'https://www.java.com/',
    icon: 'java.png',
    keywords: ['java'],
    name: 'Java',
  },
  {
    homepage: 'https://wikipedia.org/wiki/C_(programming_language)',
    icon: 'c.png',
    keywords: ['c lang'],
    name: 'C',
  },
  {
    homepage: 'https://cppreference.com/',
    icon: 'c++.png',
    keywords: ['c++ lang', 'cplusplus lang'],
    name: 'C++',
  },
  {
    homepage: 'https://dotnet.microsoft.com/languages/csharp',
    repository: 'https://github.com/dotnet/csharplang',
    icon: 'csharp.png',
    keywords: ['csharp lang', 'c# lang'],
    name: 'C#',
  },
  {
    homepage: 'https://www.swift.org/',
    repository: 'https://github.com/swiftlang/swift',
    icon: 'swift.png',
    keywords: ['swift lang'],
    name: 'Swift',
  },
  {
    homepage: 'https://kotlinlang.org/',
    repository: 'https://github.com/JetBrains/kotlin',
    icon: 'kotlin.png',
    keywords: ['kotlin lang'],
    name: 'Kotlin',
    lessRadius: true,
  },
  {
    homepage: 'https://www.r-project.org/',
    icon: 'r.png',
    keywords: ['r lang'],
    name: 'R',
  },
  {
    homepage: 'https://www.scala-lang.org/',
    repository: 'https://github.com/scala',
    icon: 'scala.png',
    keywords: ['scala lang'],
    name: 'Scala',
  },
  {
    homepage: 'https://lua.org/',
    icon: 'lua.png',
    keywords: ['lua lang'],
    name: 'Lua',
  },
  {
    homepage: 'https://www.haskell.org/',
    repository: 'https://github.com/haskell-infra',
    icon: 'haskell.png',
    keywords: ['haskell lang'],
    name: 'Haskell',
  },
  {
    homepage: 'https://www.djangoproject.com/',
    repository: 'https://github.com/django',
    icon: 'django.png',
    keywords: ['django'],
    name: 'Django',
  },
  {
    homepage: 'https://www.postgresql.org/',
    repository: 'https://github.com/postgres/postgres',
    icon: 'postgresql.png',
    keywords: ['postgresql'],
    name: 'PostgreSQL',
  },
  {
    homepage: 'https://pglite.dev/',
    repository: 'https://github.com/electric-sql/pglite',
    icon: 'pglite.png',
    keywords: ['pglite'],
    name: 'PGlite',
  },
  {
    homepage: 'https://sqlite.org/',
    repository: 'https://github.com/sqlite/sqlite',
    icon: 'sqlite.png',
    keywords: ['sqlite'],
    name: 'SQLite',
  },
  {
    homepage: 'https://www.edgedb.com/',
    repository: 'https://github.com/edgedb/edgedb',
    icon: 'edgedb.png',
    keywords: ['edgedb'],
    name: 'EdgeDB',
  },
  {
    homepage: 'https://pingcap.com/',
    repository: 'https://github.com/pingcap/tidb',
    icon: 'tidb.png',
    keywords: ['tidb'],
    name: 'TiDB',
  },
];
