export default <AppItem[]> [
  {
    homepage: [
      { href: 'https://nodejs.cn/', title: '中文官网' },
      { href: 'https://nodejs.org', title: '英文官网' },
    ],
    repository: 'https://github.com/nodejs/node/',
    icon: 'nodejs.png',
    keywords: ['nodejs'],
    name: 'NodeJS',
  },
  {
    homepage: 'https://deno.com/',
    repository: 'https://github.com/denoland',
    icon: 'deno.png',
    iconDark: 'deno_dark.png',
    keywords: ['deno'],
    name: 'Deno',
  },
  {
    homepage: 'https://bun.sh/',
    repository: 'https://github.com/oven-sh/bun',
    icon: 'bun.png',
    keywords: ['bun'],
    name: 'Bun',
  },
  {
    homepage: 'https://developers.cloudflare.com/workers/',
    repository: 'https://github.com/cloudflare/workers-sdk',
    icon: 'workers.png',
    keywords: ['workers'],
    name: 'Workers',
  },
  {
    homepage: 'https://sailsjs.com/',
    repository: 'https://github.com/balderdashy/sails',
    icon: 'sails.png',
    keywords: ['sails'],
    name: 'Sails',
  },
  {
    homepage: 'https://hono.dev/',
    repository: 'https://github.com/honojs/hono',
    icon: 'hono.png',
    keywords: ['hono'],
    name: 'Hono',
  },
  {
    homepage: 'https://elysiajs.com/',
    repository: 'https://github.com/elysiajs/elysia',
    icon: 'elysiajs.png',
    keywords: ['elysia'],
    name: 'Elysia',
  },
  {
    homepage: 'https://h3.unjs.io/',
    repository: 'https://github.com/unjs/h3',
    icon: 'h3.png',
    keywords: ['h3'],
    name: 'h3',
  },
  {
    homepage: 'https://v8.dev/',
    repository: 'https://github.com/v8/v8',
    icon: 'v8.png',
    keywords: ['v8'],
    name: 'V8',
  },
  {
    homepage: 'https://libuv.org/',
    repository: 'https://github.com/libuv/libuv',
    icon: 'libuv.png',
    keywords: ['libuv'],
    name: 'libuv',
  },
  {
    homepage: 'https://nodemon.io/',
    repository: 'https://github.com/remy/nodemon/',
    icon: 'nodemon.png',
    keywords: ['nodemon'],
    name: 'Nodemon',
  },
  {
    homepage: 'https://typestrong.org/ts-node/',
    repository: 'https://github.com/TypeStrong/ts-node',
    icon: 'ts-node.png',
    keywords: ['ts-node'],
    name: 'TSNode',
  },
  {
    homepage: 'https://tsx.is/',
    repository: 'https://github.com/privatenumber/tsx',
    icon: 'tsx.png',
    keywords: ['tsx'],
    name: 'tsx',
  },
]