export default <AppItem[]>[
  {
    homepage: [
      { href: 'https://markdown-it.github.io/', title: 'MarkdownIt' },
      { href: 'https://www.markdown.xyz/', title: 'Markdown' },
      { href: 'http://markdown.p2hp.com/basic-syntax/', title: 'Markdown' },
      { href: 'http://www.markdown.cn/', title: 'Markdown' },
    ],
    repository: 'https://github.com/markdown-it/markdown-it',
    icon: 'markdown.png',
    keywords: ['markdown'],
    name: 'Markdown',
    darkInvert: true,
  },
  {
    homepage: [{ href: 'https://apifox.com/', title: 'Apifox' }],
    repository: '',
    icon: 'apifox.png',
    keywords: ['api', 'document', 'mock', 'test'],
    name: 'Apifox',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'https://www.processon.com/', title: 'ProcessOn' },
      { href: 'https://www.omnigroup.com/omnigraffle', title: 'OmniGraffle' },
      { href: 'https://app.diagrams.net/', title: 'diagrams.net' },
    ],
    repository: '',
    icon: 'mindmap.png',
    keywords: ['mindmap', 'diagram', 'diagramming'],
    name: '思维导图',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'https://cyberduck.io', title: 'Cyberduck' },
      { href: 'http://fivedetails.com/flow/', title: 'Flow' },
      { href: 'https://localsend.org/', title: 'LocalSend' },
      { href: 'https://github.com/grishka/NearDrop', title: 'NearDrop' },
      { href: 'https://panic.com/transmit/', title: 'Transmit' },
      { href: 'http://www.yummysoftware.com', title: 'Yummy FTP' },
    ],
    repository: '',
    icon: 'filesharing.png',
    keywords: ['ftp', 'sftp', 'file', 'transfer', 'share'],
    name: '文件共享',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'http://www.videolan.org/', title: 'VLC' },
      { href: 'https://github.com/iina/iina', title: 'IINA' },
      { href: 'https://www.shotcut.org', title: 'Shotcut' },
      {
        href: 'https://www.blackmagicdesign.com/products/davinciresolve/',
        title: 'DaVinci Resolve',
      },
      { href: 'https://ardour.org/', title: 'Ardour' },
      { href: 'http://www.audacityteam.org/', title: 'Audacity' },
    ],
    repository: '',
    icon: 'audio-video.png',
    keywords: ['audio', 'video', 'media', 'player', 'editor'],
    name: '音频与视频',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'https://agenda.com/', title: 'Agenda' },
      { href: 'http://www.bear-writer.com/', title: 'Bear Writer' },
      { href: 'https://boostnote.io/', title: 'Boostnote' },
    ],
    repository: '',
    icon: 'diary.png',
    keywords: ['diary', 'journal', 'notes', 'planner'],
    name: '日记',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'https://obsidian.md', title: 'Obsidian' },
      { href: 'https://www.notion.so/zh-cn', title: 'Notion' },
      { href: 'https://evernote.com/', title: 'Evernote' },
      { href: 'https://logseq.com/', title: 'Logseq' },
      { href: 'https://www.yuque.com/install/desktop', title: '语雀' },
      { href: 'http://note.youdao.com/', title: '有道云笔记' },
    ],
    repository: '',
    icon: 'notes.png',
    keywords: ['notes', 'notebook', 'knowledge', 'markdown'],
    name: '笔记',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'http://www.typora.io/', title: 'Typora' },
      { href: 'https://www.ulyssesapp.com/features/', title: 'Ulysses' },
      { href: 'https://www.momothink.com/wonderpen', title: 'WonderPen' },
      { href: 'https://ivarptr.github.io/yu-writer.site/', title: 'Yu Writer' },
      { href: 'https://ia.net/writer/', title: 'iA Writer' },
    ],
    repository: '',
    icon: 'writing.png',
    keywords: ['writing', 'markdown', 'editor', 'author'],
    name: '写作',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'http://calibre-ebook.com/', title: 'Calibre' },
      { href: 'https://sigil-ebook.com/', title: 'Sigil' },
      {
        href: 'https://apps.apple.com/cn/app/kindle-%E7%94%B5%E5%AD%90%E9%98%85%E8%AF%BB%E5%99%A8/id302584613',
        title: 'Kindle App',
      },
      { href: 'https://readest.com', title: 'Readest' },
      { href: 'https://janereader.com/', title: 'Jane Reader' },
    ],
    repository: '',
    icon: 'ebook.png',
    keywords: ['ebook', 'book', 'reader', 'epub', 'calibre'],
    name: '电子书',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'https://aria2.github.io/', title: 'aria2' },
      {
        href: 'https://software.charliemonroe.net/downie.php',
        title: 'Downie',
      },
      { href: 'https://www.freedownloadmanager.org/', title: 'FDM' },
      { href: 'https://motrix.app/', title: 'Motrix' },
      { href: 'https://www.qbittorrent.org/', title: 'qBittorrent' },
      { href: 'https://www.transmissionbt.com/', title: 'Transmission' },
      { href: 'https://you-get.org/', title: 'You-Get' },
      { href: 'https://github.com/yt-dlp/yt-dlp', title: 'yt-dlp' },
    ],
    repository: '',
    icon: 'download.png',
    keywords: ['download', 'torrent', 'manager', 'aria2', 'downloader'],
    name: '下载工具',
    darkInvert: false,
  },
  {
    homepage: [
      { href: 'http://www.2doapp.com/', title: '2Do' },
      { href: 'https://flexibits.com/fantastical', title: 'Fantastical' },
      { href: 'https://masterbuilders.io', title: 'Focus' },
      { href: 'https://todo.microsoft.com/', title: 'Microsoft To-Do' },
      { href: 'https://www.omnigroup.com/omnifocus/', title: 'OmniFocus' },
      { href: 'https://todoist.com/mac', title: 'Todoist' },
      { href: 'https://www.dida365.com/', title: '滴答清单' },
      { href: 'https://culturedcode.com/things/', title: 'Things' },
    ],
    repository: '',
    icon: 'todo.png',
    keywords: ['todo', 'task', 'productivity', 'gtd', 'planner'],
    name: '待办事项',
    darkInvert: false,
  },
];
